language: node_js

# Use latest version of Node.js
node_js:
  - lts/*

# Scripts to run to test application
script:
  - npm test

# Scripts to run after build success/failure
after_success:
  - npm run coverage
  - wget https://raw.githubusercontent.com/NGCP/GCS/master/script/webhook.sh
  - chmod +x webhook.sh
  - ./webhook.sh success
after_failure:
  - wget https://raw.githubusercontent.com/NGCP/GCS/master/script/webhook.sh
  - chmod +x webhook.sh
  - ./webhook.sh failure
