language: node_js

# Use latest version of Node.js
node_js:
  - lts/*

# Cache node_modules after testing
cache: npm

# Scripts to run to test application
script:
  # Running "npm test" in TravisCI will run all scripts in parallel so this is to force them
  # to run in sequence
  - npm run test:lint
  - npm run test:unit

# Run coverage after tests pass
after_success: npm run coverage
